README.md, lib/aliasRestructureStack.js, lib/removeAlias.js
Fixes #7 Events are subscribed to the alias they are deployed to. Same as with SLS 0.5. Fixed a small issue with alias remove in case of empty IAM refs.
=> Issue #7 event support

index.js, lib/validate.js, package.json, test/index.test.js, test/validate.test.js
Closes #20 
Hook new lifecycle events. Check serverless version.
=> Use lifecycles provided by SLS 1.12 and later.

lib/createAliasStack.js, test/createAliasStack.test.js, test/validate.test.js
Relates to #29 
This PR adds unit tests and increases code coverage and functional tests.
=> Added unit tests

README.md, lib/aliasRestructureStack.js, lib/stackops/apiGateway.js
Closes #32 
Added support for CW events. Events deployed in a stage will now trigger the aliased functions correctly.
Added Interoperability section to README to give advice for integrating other plugins.
Set the SERVERLESS_ALIAS environment variable automatically, to allow functions to access the currently invoked function alias.
=> Support CW events.

.travis.yml, index.js, lib/aliasRestructureStack.js, lib/collectUserResources.js, lib/stackops/lambdaRole.js, lib/stackops/userResources.js, package.json, test/index.test.js, test/stackops/lambdaRole.test.js
Fixes #36 
Now every aliased function uses the alias role. That allows to deploy different role configurations per alias. It improves adding new resources with permissions on a separate branch.
=> Use separate role per alias. Fix user resource detection.

README.md, index.js, lib/listAliases.js, lib/logs.js, lib/stackInformation.js, package.json, test/logs.test.js
Fixes #38 
Added logs command that uses a given alias option or defaults to the master alias.
All functionaliy of the Serverless logs command is supported.
=> Support sls logs command

README.md, lib/stackops/apiGateway.js
Closes #40 
The stage variable SERVERLESS_ALIAS is now used to set the alias in ApiGateway.
Now you can use the AWS console correctly to invoke a specific aliased function version.
=> Use stage variable to set alias in APIG

index.js, lib/validate.js, test/configureAliasStack.test.js, test/createAliasStack.test.js, test/index.test.js, test/validate.test.js
Fixes #45 
The initialization of `stage` and `stackName` are moved to `validate()`. This makes sure, that the service configuration has been prepared properly (variable substitution) and is ready to be used.
With the introduction of promised variable retrieval, timings have changed in SLS.
=> Fix stage name retrieval

README.md, lib/aliasRestructureStack.js, lib/stackops/snsEvents.js, test/aliasRestructureStack.test.js, test/data/sns-stack.json, test/stackops/snsEvents.test.js
Closes #43 
SNS Topics and subscriptions are now part of the alias, i.e. the topic name is appended with the alias name and the lambda subscriptions point to the associated function aliases.
This solution follows the discussion in #43
=> Transform SNS elements and move them to the alias stack.

lib/stackops/apiGateway.js, test/stackops/init.test.js
Closes #22 
Custom authorizer support. Authorizer URIs point to the aliased function version and the authorizer name is appended with the alias name.
The authorizer will be deployed into the APIG stage. If a different alias is deployed that does not contain an authorizer, it will disappear from the API staging area (console), **but remains deployed within the correct stage**. This is expected behavior, because an APIG deployment to a stage will deploy the complete staging area - so everything not part of the current deployment has to be removed.
From a functional perspective the deployed APIs remain completely intact.
=> Set authorizer name and Uri

lib/stackops/apiGateway.js, test/data/auth-stack.json, test/stackops/apiGateway.test.js
Fixes #51 
The plugin should leave all non-Lambda authorizers as they are. Only Lambda authorizers have an URI that needs to be adapted for alias deployments.
=> Only change authorizer uris on TOKEN type authorizers

lib/stackops/lambdaRole.js, test/aliasRestructureStack.test.js, test/configureAliasStack.test.js, test/stackops/init.test.js, test/stackops/lambdaRole.test.js, test/stackops/snsEvents.test.js
Fixes #50 
Retain only IAM roles of currently deployed aliases.
Make sure that only fresh data is used in unit tests. Required data must be cloned, as otherwise the cached version is modified by the tests and reloaded on subsequent ones.
=> Remove superfluous iam roles

index.js
Relates to #49 
Set `provider.alias` on plugin initialization. This will lead to the proper variable substitution.
=> Set provider.alias variable to unresolved values in init.

README.md, index.js, lib/removeAlias.js, lib/validate.js, test/data/alias-stack-2.json, test/removeAlias.test.js
Fixes #56 
As soon as all deployed aliases have been removed, it is possible to remove the service by removing the master alias.
=> Removal of master alias

README.md, lib/stackops/apiGateway.js, test/stackops/apiGateway.test.js
Implements #57 
Full APIG configuration is now available on service, function and endpoint levels.
=> Stage configuration

lib/updateAliasStack.js, lib/uploadAliasArtifacts.js, test/updateAliasStack.test.js, test/uploadAliasArtifacts.test.js
Closes #63 
Apply the SSE configuration from serverless.yml if present. The plugin now follows the same procedure as Serverless does.
Additionally added support for the cfnRole property.
=> Support S3 server side encryption

README.md, index.js, lib/updateFunctionAlias.js, package-lock.json
Closes #29 
The version deployed by `serverless deploy function` now gets versioned (persisted) and labeled with the correct alias. The operation demands setting the `--force` switch because Serverless just might drop the deployment if nothing changed which would put the alias to a wrong version. Serverless does not tell anything about the skip to anyone :(
=> Support serverless deploy function

.gitignore, lib/stackops/apiGateway.js, test/stackops/apiGateway.test.js
Fixes: #80
According to AWS, stage configurations have to refer to '*' to catch all methods or paths.
In case of endpoints defined with `ANY` as method, we have to use `*` as method.
=> Support ANY type endpoints with stage configuration

lib/validate.js, test/validate.test.js
Fixes #72 
The warmup plugin (and maybe others as well) uses the SERVERLESS_ALIAS environment variable to determine if the functions are deployed to a specific alias.
Until now the variable was only available at runtime, so the evaluation failed.
It is now set in the validate() function, so that the plugins can easily grab it.
=> Set SERVERLESS_ALIAS during build

lib/stackops/snsEvents.js, test/data/sns-stack.json, test/stackops/snsEvents.test.js
Closes #94 
This PR adds support for resources of type AWS::SNS::Subscription to be transferred to the alias stack. This resource will be present in the cloudformation template when a lambda subscribes to an existing SNS topic by ARN.
=> Added support to have an alias subscribe to an existing SNS topic #94

lib/stackops/apiGateway.js, test/data/auth-stack.json, test/stackops/apiGateway.test.js
Closes #96 
Added support for authorizers of type **REQUEST** to have ${stageVariables.SERVERLESS_ALIAS} appended to the arn. Currently this is only happening for authorizers that are of type **TOKEN**.
=> Added support to append ${stageVariables.SERVERLESS_ALIAS} to authorizers of type REQUEST #96

index.js, lib/logs.js, lib/stackInformation.js, test/logs.test.js
* alias logs will now pull the latest version logs from “Lambda”
service directly if --version flag is not specificed.
* Added --version flag to alias logs, so that user can view logs of a
specific version of function.
Closes #89 
Closes #62
=> Enhance alias logs function #89 #62

lib/stackops/apiGateway.js, test/data/auth-stack-2.json, test/stackops/apiGateway.test.js
Proposed solution for #101 
After digging a bit I found this bit in apiGateway.js
const funcIndex = _.findIndex(uriParts, part => _.has(part, 'Fn::GetAtt'));
which selects the index in the `AuthorizerUri. Fn::Join` array based on finding the `GetAtt , ARN` of a referenced lambda function. This won't work if the function is directly referenced using its ARN. In this case the uriPart of the `AuthorizerUri` will simply be a string with the ARN and `funcIndex` will be set to -1. Hence `${stageVariables.SERVERLESS_ALIAS}` will be added to the head of the array. 
I would suggest to add a simple check for strings, e.g.
const funcIndex = _.findIndex(uriParts, part =>
_.has(part, 'Fn::GetAtt') || _.startsWith(part, 'arn:aws:lambda'));
Concerning the missing `FunctionName` I would simple use the …
=> Add support for referenced custom authorizer lambdas

.gitignore, README.md, package.json
Fixes: https://github.com/serverless-heaven/serverless-aws-alias/issues/160
`README.md` and `package.json` updated
PS: I'm not totally sure about coverage url, pls check.
PPS: gitignore updated with IDE, Platform, Coverage and Code style specific files
=> Links update after repo move to serverless-heaven

package-lock.json, package.json, test/aliasRestructureStack.test.js, test/configureAliasStack.test.js, test/createAliasStack.test.js, test/index.test.js, test/logs.test.js, test/removeAlias.test.js, test/stackops/apiGateway.test.js, test/stackops/init.test.js, test/stackops/lambdaRole.test.js, test/stackops/snsEvents.test.js, test/updateAliasStack.test.js, test/uploadAliasArtifacts.test.js
dependencies are obsolete and have a lot of vulnerabilities.
current `npm audit` says: `found 79 vulnerabilities (35 low, 35 moderate, 9 high) in 1656 scanned packages`
PR contains updated dependencies and fix for sinon deprecated methods.
=> fix for: dependencies are obsolete and have a lot of vulnerabilities

.gitignore, lib/stackops/apiGateway.js, lib/stackops/snsEvents.js, lib/utils.js, test/data/alias-stack-1.json, test/data/sls-stack-1.json, test/stackops/apiGateway.test.js
.find would find wrong versionname and aliasname
Example:
Function A: GetAccount
Function B: GetAccountByName
For function GetAccountByName the versionname and aliasname would be from the GetAccount function
=> Fix for functionnames where functionname A startwith functionname B

lib/stackops/lambdaRole.js, test/data/sls-stack-3.json, test/stackops/lambdaRole.test.js, test/updateAliasStack.test.js
duplicate of https://github.com/HyperBrain/serverless-aws-alias/pull/145 with tests written for case when function has custom role name.
=> Tests for - fix the case of per-function custom Role

lib/stackops/lambdaRole.js
I had a trouble with per-function custom Role, and needed to fix it.
I llooked around issues and pull requests, and found #87 and #88.
My custom role is in the same stack, so @bencodner 's solution does not apply.
So, I wrote another patch. It will cover cross-stack cases.
=> fix the case of per-function custom Role

lib/utils.js
Fixes #159  by reverting code introduced in #162 
I overlooked that versions and alias will have a generated suffix. This will lead to errors, when using `===` instead of `_.startsWith`
=> replace equals with startsWith in util functions

lib/removeAlias.js, lib/stackops/apiGateway.js
Replacing the `-` in the alias for the API Gateway template name. Without this change, chosing an alias name with `-` in it while your definition has an API Gateway with authorizers in it will fail.
=> Supporting dash in alias name when creating api gateway authorizers

README.md, lib/aliasRestructureStack.js, lib/removeAlias.js, lib/stackops/apiGateway.js, lib/validate.js, test/aliasRestructureStack.test.js, test/data/sls-stack-2.json, test/removeAlias.test.js, test/updateAliasStack.test.js
This fixes #127 and will allow the master alias name to be selected by a command line option `sls deploy --masterAlias <masterAlias>`. The master alias name will be exported in the base stack as value and will be used upon removal of the stack.
=> allow configurable master alias

README.md, lib/stackops/functions.js, lib/validate.js
By default, versions are given the "Delete" retention policy. @HyperBrain gave a brief explanation why in issue #122. However, there are usecases and alias workflows where retaining previous versions is less risky. This PR adds a `--retain` flag which gives users an option for opting into retaining versions.
=> Option to retain versions

.travis.yml, README.md, package-lock.json, package.json
* brings fresh abilities + fixes vulnerabilities
* changelog updated
=> Drop node 6 support + update dependencies

README.md
The serverless framework makes use of npm, but is designed to allow deployment to services such as AWS which support a variety of languages. As a result, there are users utilizing the serverless tool who are not as familiar with npm commands. 
This change adds the explicit command syntax needed to accomplish the installation to the README install instructions
=> Clarify install for less-experienced npm users
